AWSTemplateFormatVersion: "2010-09-09"
Description: Claudiu DynamoDB Tables - Rooms Feature

Resources:
        RoomsTable:
                Type: AWS::DynamoDB::Table
                Properties:
                        TableName: claudiu-rooms
                        BillingMode: PAY_PER_REQUEST
                        AttributeDefinitions:
                                - AttributeName: roomCode
                                  AttributeType: S
                                - AttributeName: matchId
                                  AttributeType: S
                        KeySchema:
                                - AttributeName: roomCode
                                  KeyType: HASH
                        GlobalSecondaryIndexes:
                                - IndexName: matchId-index
                                  KeySchema:
                                          - AttributeName: matchId
                                            KeyType: HASH
                                  Projection:
                                          ProjectionType: ALL
                        TimeToLiveSpecification:
                                AttributeName: TTL
                                Enabled: true

Outputs:
        RoomsTableName:
                Value: !Ref RoomsTable
                Export:
                        Name: claudiu-rooms-table

        RoomsTableArn:
                Value: !GetAtt RoomsTable.Arn
                Export:
                        Name: claudiu-rooms-table-arn
