AWSTemplateFormatVersion: "2010-09-09"

Description: Claudiu API Gateway CloudWatch Logging Role

Resources:
        ApiGatewayCloudWatchRole:
                Type: AWS::IAM::Role

                Properties:
                        RoleName: claudiu-apigateway-cloudwatch-role

                        AssumeRolePolicyDocument:
                                Version: "2012-10-17"

                                Statement:
                                        - Effect: Allow

                                          Principal:
                                                  Service: apigateway.amazonaws.com

                                          Action: sts:AssumeRole

                        ManagedPolicyArns:
                                - arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs

Outputs:
        RoleArn:
                Value: !GetAtt ApiGatewayCloudWatchRole.Arn

                Export:
                        Name: claudiu-apigateway-cloudwatch-role-arn
